-- MySQL Script generated by MySQL Workbench
-- Sat Jul 29 22:46:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema malf_testDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema malf_testDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `malf_testDB` DEFAULT CHARACTER SET utf8mb3 ;
USE `malf_testDB` ;

-- -----------------------------------------------------
-- Table `malf_testDB`.`user_id`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`user_id` (
  `user_uniq_id` VARCHAR(45) NOT NULL,
  `account_type` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NULL,
  PRIMARY KEY (`user_uniq_id`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `user_uniq_id_UNIQUE` (`user_uniq_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malf_testDB`.`post_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`post_category` (
  `category_id` INT NOT NULL,
  `detail` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malf_testDB`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `written_time` DATETIME NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `picture` TEXT NULL DEFAULT NULL,
  `capacity` TINYINT NOT NULL,
  `location` VARCHAR(45) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `user_uniq_id` VARCHAR(45) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `fk_post_user_id1_idx` (`user_uniq_id` ASC) VISIBLE,
  INDEX `fk_post_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_user_id1`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `malf_testDB`.`post_category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `malf_testDB`.`user_require_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`user_require_info` (
  `user_uniq_id` VARCHAR(45) NOT NULL,
  `user_type` INT NOT NULL,
  `nation` INT NOT NULL,
  `gender` INT NOT NULL,
  `nick_name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `default_language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_uniq_id`),
  INDEX `fk_user_user_id1_idx` (`user_uniq_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_id1`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `malf_testDB`.`kakao_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`kakao_account` (
  `user_uniq_id` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_uniq_id`, `e_mail`),
  INDEX `fk_kakao_account_user_id1_idx` (`user_uniq_id` ASC) VISIBLE,
  CONSTRAINT `fk_kakao_account_user_id1`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malf_testDB`.`line_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`line_account` (
  `user_uniq_id` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_uniq_id`, `e_mail`),
  INDEX `fk_line_account_user_id_idx` (`user_uniq_id` ASC) VISIBLE,
  CONSTRAINT `fk_line_account_user_id`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malf_testDB`.`google_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`google_account` (
  `user_uniq_id` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_uniq_id`, `e_mail`),
  INDEX `fk_google_account_user_id1_idx` (`user_uniq_id` ASC) VISIBLE,
  CONSTRAINT `fk_google_account_user_id1`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malf_testDB`.`local_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`local_account` (
  `user_uniq_id` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`user_uniq_id`, `e_mail`),
  INDEX `fk_local_account_user_id1_idx` (`user_uniq_id` ASC) VISIBLE,
  CONSTRAINT `fk_local_account_user_id1`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malf_testDB`.`user_additional_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`user_additional_info` (
  `user_uniq_id` VARCHAR(45) NOT NULL,
  `description` TEXT NULL,
  `able_language` VARCHAR(45) NULL,
  `interests` VARCHAR(45) NULL,
  `profile_pic` VARCHAR(45) NULL,
  PRIMARY KEY (`user_uniq_id`),
  CONSTRAINT `fk_user_additional_info_user_id1`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malf_testDB`.`post_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`post_like` (
  `post_id` INT NOT NULL,
  `user_uniq_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`post_id`, `user_uniq_id`),
  INDEX `fk_post_has_user_id_user_id1_idx` (`user_uniq_id` ASC) VISIBLE,
  INDEX `fk_post_has_user_id_post1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_has_user_id_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `malf_testDB`.`post` (`post_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_has_user_id_user_id1`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `malf_testDB`.`post_participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`post_participation` (
  `post_post_id` INT NOT NULL,
  `user_uniq_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`post_post_id`, `user_uniq_id`),
  INDEX `fk_post_has_user_id_user_id2_idx` (`user_uniq_id` ASC) VISIBLE,
  INDEX `fk_post_has_user_id_post2_idx` (`post_post_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_has_user_id_post2`
    FOREIGN KEY (`post_post_id`)
    REFERENCES `malf_testDB`.`post` (`post_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_has_user_id_user_id2`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `malf_testDB`.`user_ban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`user_ban` (
  `user_uniq_id` VARCHAR(45) NOT NULL,
  `banned_user_uniq_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_uniq_id`, `banned_user_uniq_id`),
  INDEX `fk_user_id_has_user_id_user_id2_idx` (`banned_user_uniq_id` ASC) VISIBLE,
  INDEX `fk_user_id_has_user_id_user_id1_idx` (`user_uniq_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_id_has_user_id_user_id1`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_user_id_has_user_id_user_id2`
    FOREIGN KEY (`banned_user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malf_testDB`.`account_ban`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`account_ban` (
  `user_uniq_id` VARCHAR(45) NOT NULL,
  `account_bancol` VARCHAR(45) NULL,
  PRIMARY KEY (`user_uniq_id`),
  CONSTRAINT `fk_account_ban_user_id1`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malf_testDB`.`post_want_join`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`post_want_join` (
  `post_id` INT NOT NULL,
  `user_uniq_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`post_id`, `user_uniq_id`),
  INDEX `fk_post_has_user_id_user_id3_idx` (`user_uniq_id` ASC) VISIBLE,
  INDEX `fk_post_has_user_id_post3_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_has_user_id_post3`
    FOREIGN KEY (`post_id`)
    REFERENCES `malf_testDB`.`post` (`post_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_has_user_id_user_id3`
    FOREIGN KEY (`user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `malf_testDB`.`meeting_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`meeting_review` (
  `post_id` INT NOT NULL,
  `reviewed_user_uniq_id` VARCHAR(45) NOT NULL,
  `review_writer_user_uniq_id` VARCHAR(45) NOT NULL,
  `score` FLOAT NULL,
  PRIMARY KEY (`post_id`, `reviewed_user_uniq_id`, `review_writer_user_uniq_id`),
  INDEX `fk_post_has_user_id_user_id4_idx` (`reviewed_user_uniq_id` ASC) VISIBLE,
  INDEX `fk_post_has_user_id_post4_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_meeting_review_user_id1_idx` (`review_writer_user_uniq_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_has_user_id_post4`
    FOREIGN KEY (`post_id`)
    REFERENCES `malf_testDB`.`post` (`post_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_post_has_user_id_user_id4`
    FOREIGN KEY (`reviewed_user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_meeting_review_user_id1`
    FOREIGN KEY (`review_writer_user_uniq_id`)
    REFERENCES `malf_testDB`.`user_id` (`user_uniq_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `malf_testDB`.`review_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`review_category` (
  `category_id` INT NOT NULL,
  `detail` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `malf_testDB`.`meeting_review_has_review_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`meeting_review_has_review_category` (
  `post_id` INT NOT NULL,
  `reviewed_user_uniq_id` VARCHAR(45) NOT NULL,
  `review_writer_user_uniq_id` VARCHAR(45) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `reviewed_user_uniq_id`, `review_writer_user_uniq_id`, `category_id`),
  INDEX `fk_meeting_review_has_review_category_review_category1_idx` (`category_id` ASC) VISIBLE,
  INDEX `fk_meeting_review_has_review_category_meeting_review1_idx` (`post_id` ASC, `reviewed_user_uniq_id` ASC, `review_writer_user_uniq_id` ASC) VISIBLE,
  CONSTRAINT `fk_meeting_review_has_review_category_meeting_review1`
    FOREIGN KEY (`post_id` , `reviewed_user_uniq_id` , `review_writer_user_uniq_id`)
    REFERENCES `malf_testDB`.`meeting_review` (`post_id` , `reviewed_user_uniq_id` , `review_writer_user_uniq_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_meeting_review_has_review_category_review_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `malf_testDB`.`review_category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `malf_testDB`.`chat_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `malf_testDB`.`chat_info` (
  `post_post_id` INT NOT NULL,
  PRIMARY KEY (`post_post_id`),
  CONSTRAINT `fk_chat_info_post1`
    FOREIGN KEY (`post_post_id`)
    REFERENCES `malf_testDB`.`post` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
